apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadhcjt6827-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadhcjt6827-tenant-component
    app.kubernetes.io/part-of: loadhcjt6827-tenant-app
  name: loadhcjt6827-tenant-component
  namespace: loadhcjt6827-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadhcjt6827-tenant-component
    weight: null
status: {}
