apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadhcjt6827-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadhcjt6827-tenant-component
    app.kubernetes.io/part-of: loadhcjt6827-tenant-app
  name: loadhcjt6827-tenant-component
  namespace: loadhcjt6827-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadhcjt6827-tenant-component
status:
  loadBalancer: {}
